/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LabWalletsRouteImport } from './routes/lab.wallets'
import { Route as LabUtxosRouteImport } from './routes/lab.utxos'
import { Route as LabTransactionsRouteImport } from './routes/lab.transactions'
import { Route as LabNetworksRouteImport } from './routes/lab.networks'
import { Route as LabMiningRouteImport } from './routes/lab.mining'
import { Route as LabMempoolRouteImport } from './routes/lab.mempool'
import { Route as LabChallengesRouteImport } from './routes/lab.challenges'
import { Route as LabBlockchainRouteImport } from './routes/lab.blockchain'
import { Route as LabBitcoinCoreRouteImport } from './routes/lab.bitcoin-core'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabWalletsRoute = LabWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => LabRoute,
} as any)
const LabUtxosRoute = LabUtxosRouteImport.update({
  id: '/utxos',
  path: '/utxos',
  getParentRoute: () => LabRoute,
} as any)
const LabTransactionsRoute = LabTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LabRoute,
} as any)
const LabNetworksRoute = LabNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => LabRoute,
} as any)
const LabMiningRoute = LabMiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => LabRoute,
} as any)
const LabMempoolRoute = LabMempoolRouteImport.update({
  id: '/mempool',
  path: '/mempool',
  getParentRoute: () => LabRoute,
} as any)
const LabChallengesRoute = LabChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => LabRoute,
} as any)
const LabBlockchainRoute = LabBlockchainRouteImport.update({
  id: '/blockchain',
  path: '/blockchain',
  getParentRoute: () => LabRoute,
} as any)
const LabBitcoinCoreRoute = LabBitcoinCoreRouteImport.update({
  id: '/bitcoin-core',
  path: '/bitcoin-core',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab/bitcoin-core': typeof LabBitcoinCoreRoute
  '/lab/blockchain': typeof LabBlockchainRoute
  '/lab/challenges': typeof LabChallengesRoute
  '/lab/mempool': typeof LabMempoolRoute
  '/lab/mining': typeof LabMiningRoute
  '/lab/networks': typeof LabNetworksRoute
  '/lab/transactions': typeof LabTransactionsRoute
  '/lab/utxos': typeof LabUtxosRoute
  '/lab/wallets': typeof LabWalletsRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/bitcoin-core': typeof LabBitcoinCoreRoute
  '/lab/blockchain': typeof LabBlockchainRoute
  '/lab/challenges': typeof LabChallengesRoute
  '/lab/mempool': typeof LabMempoolRoute
  '/lab/mining': typeof LabMiningRoute
  '/lab/networks': typeof LabNetworksRoute
  '/lab/transactions': typeof LabTransactionsRoute
  '/lab/utxos': typeof LabUtxosRoute
  '/lab/wallets': typeof LabWalletsRoute
  '/lab': typeof LabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab/bitcoin-core': typeof LabBitcoinCoreRoute
  '/lab/blockchain': typeof LabBlockchainRoute
  '/lab/challenges': typeof LabChallengesRoute
  '/lab/mempool': typeof LabMempoolRoute
  '/lab/mining': typeof LabMiningRoute
  '/lab/networks': typeof LabNetworksRoute
  '/lab/transactions': typeof LabTransactionsRoute
  '/lab/utxos': typeof LabUtxosRoute
  '/lab/wallets': typeof LabWalletsRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab/bitcoin-core'
    | '/lab/blockchain'
    | '/lab/challenges'
    | '/lab/mempool'
    | '/lab/mining'
    | '/lab/networks'
    | '/lab/transactions'
    | '/lab/utxos'
    | '/lab/wallets'
    | '/lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab/bitcoin-core'
    | '/lab/blockchain'
    | '/lab/challenges'
    | '/lab/mempool'
    | '/lab/mining'
    | '/lab/networks'
    | '/lab/transactions'
    | '/lab/utxos'
    | '/lab/wallets'
    | '/lab'
  id:
    | '__root__'
    | '/'
    | '/lab/bitcoin-core'
    | '/lab/blockchain'
    | '/lab/challenges'
    | '/lab/mempool'
    | '/lab/mining'
    | '/lab/networks'
    | '/lab/transactions'
    | '/lab/utxos'
    | '/lab/wallets'
    | '/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabIndexRoute: typeof LabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/wallets': {
      id: '/lab/wallets'
      path: '/wallets'
      fullPath: '/lab/wallets'
      preLoaderRoute: typeof LabWalletsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/utxos': {
      id: '/lab/utxos'
      path: '/utxos'
      fullPath: '/lab/utxos'
      preLoaderRoute: typeof LabUtxosRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/transactions': {
      id: '/lab/transactions'
      path: '/transactions'
      fullPath: '/lab/transactions'
      preLoaderRoute: typeof LabTransactionsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/networks': {
      id: '/lab/networks'
      path: '/networks'
      fullPath: '/lab/networks'
      preLoaderRoute: typeof LabNetworksRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/mining': {
      id: '/lab/mining'
      path: '/mining'
      fullPath: '/lab/mining'
      preLoaderRoute: typeof LabMiningRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/mempool': {
      id: '/lab/mempool'
      path: '/mempool'
      fullPath: '/lab/mempool'
      preLoaderRoute: typeof LabMempoolRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/challenges': {
      id: '/lab/challenges'
      path: '/challenges'
      fullPath: '/lab/challenges'
      preLoaderRoute: typeof LabChallengesRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/blockchain': {
      id: '/lab/blockchain'
      path: '/blockchain'
      fullPath: '/lab/blockchain'
      preLoaderRoute: typeof LabBlockchainRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/bitcoin-core': {
      id: '/lab/bitcoin-core'
      path: '/bitcoin-core'
      fullPath: '/lab/bitcoin-core'
      preLoaderRoute: typeof LabBitcoinCoreRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabIndexRoute: LabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
